### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by WebFreak001** [alphaKAI/unlocker#1]
First it will complain about libpafe4d missing because you have included your dub.selections.json which references it in the parent folder (just deleting the file fixed that) but then a compilation error occurs in libpafe4d (did you push and tag your changes required for this?)

```
libusb-d 0.1.1: building configuration "library"...
libpafe4d 0.0.1: building configuration "library"...
../../.dub/packages/libusb-d-0.1.1/libusb-d/src/libusb/package.d(38,10): Error: module consts is in file 'consts.d' which cannot be read
import path[0] = ../../.dub/packages/libpafe4d-0.0.1/libpafe4d/source/
import path[1] = ../../.dub/packages/libusb-d-0.1.1/libusb-d/src/
import path[2] = /usr/include/dlang/dmd
dmd failed with exit code 1.
```

**Comment by alphaKAI** [comment]
umm... The error doesn't happen on my environment, please check whether libusb and libpafe is installed.

**Comment by WebFreak001** [comment]
was on old commit, fixed now
